"""Initial migration with indexes

Revision ID: 12aa197acd99
Revises: 
Create Date: 2026-06-24 00:54:08.192049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import LightingLevel, CrowdDensity, SeverityLevel


# revision identifiers, used by Alembic.
revision: str = '12aa197acd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'safety_nodes',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('latitude', sa.Float, nullable=False),
        sa.Column('longitude', sa.Float, nullable=False),
        sa.Column('safety_score', sa.Float, nullable=False),
        sa.Column('lighting_level', sa.Enum(LightingLevel), nullable=False),
        sa.Column('crowd_density', sa.Enum(CrowdDensity), nullable=False),
        sa.Column('updated_at', sa.DateTime, nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_safety_nodes_lat_lon', 'safety_nodes', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_safety_nodes_latitude'), 'safety_nodes', ['latitude'], unique=False)
    op.create_index(op.f('ix_safety_nodes_longitude'), 'safety_nodes', ['longitude'], unique=False)
    op.create_index(op.f('ix_safety_nodes_lighting_level'), 'safety_nodes', ['lighting_level'], unique=False)
    op.create_index(op.f('ix_safety_nodes_crowd_density'), 'safety_nodes', ['crowd_density'], unique=False)
    op.create_index(op.f('ix_safety_nodes_updated_at'), 'safety_nodes', ['updated_at'], unique=False)

    op.create_table(
        'crime_hotspots',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('latitude', sa.Float, nullable=False),
        sa.Column('longitude', sa.Float, nullable=False),
        sa.Column('radius', sa.Float, nullable=False),
        sa.Column('severity', sa.Enum(SeverityLevel), nullable=False),
        sa.Column('description', sa.String(500), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crime_hotspots_lat_lon', 'crime_hotspots', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_crime_hotspots_latitude'), 'crime_hotspots', ['latitude'], unique=False)
    op.create_index(op.f('ix_crime_hotspots_longitude'), 'crime_hotspots', ['longitude'], unique=False)
    op.create_index(op.f('ix_crime_hotspots_severity'), 'crime_hotspots', ['severity'], unique=False)

    op.create_table(
        'user_reports',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('latitude', sa.Float, nullable=False),
        sa.Column('longitude', sa.Float, nullable=False),
        sa.Column('report_type', sa.String(100), nullable=False),
        sa.Column('timestamp', sa.DateTime, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_reports_lat_lon', 'user_reports', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_user_reports_latitude'), 'user_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_user_reports_longitude'), 'user_reports', ['longitude'], unique=False)
    op.create_index(op.f('ix_user_reports_report_type'), 'user_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_user_reports_timestamp'), 'user_reports', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_reports_is_active'), 'user_reports', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reports')
    op.drop_table('crime_hotspots')
    op.drop_table('safety_nodes')
    # ### end Alembic commands ###
