"""add_accident_risk_tables

Revision ID: 6fc9b1c4c063
Revises: 12aa197acd99
Create Date: 2026-06-27 18:49:34.382409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc9b1c4c063'
down_revision: Union[str, Sequence[str], None] = '12aa197acd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highway_black_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='blackspotseverity'), nullable=False),
    sa.Column('accident_count', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('last_accident_date', sa.DateTime(), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highway_black_spots_id'), 'highway_black_spots', ['id'], unique=False)
    op.create_index('ix_highway_black_spots_lat_lon', 'highway_black_spots', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_highway_black_spots_latitude'), 'highway_black_spots', ['latitude'], unique=False)
    op.create_index(op.f('ix_highway_black_spots_longitude'), 'highway_black_spots', ['longitude'], unique=False)
    op.create_index(op.f('ix_highway_black_spots_severity'), 'highway_black_spots', ['severity'], unique=False)
    op.create_table('road_segment_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('segment_length_m', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('accident_frequency', sa.Float(), nullable=True),
    sa.Column('severity_distribution', sa.String(length=500), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('last_accident_date', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_segment_risks_id'), 'road_segment_risks', ['id'], unique=False)
    op.create_index('ix_road_segment_risks_lat_lon', 'road_segment_risks', ['start_latitude', 'start_longitude'], unique=False)
    op.create_index('ix_road_segment_risks_score', 'road_segment_risks', ['risk_score'], unique=False)
    op.create_index(op.f('ix_road_segment_risks_start_latitude'), 'road_segment_risks', ['start_latitude'], unique=False)
    op.create_index(op.f('ix_road_segment_risks_start_longitude'), 'road_segment_risks', ['start_longitude'], unique=False)
    op.create_table('accident_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('black_spot_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accident_date', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('FATAL', 'GRIEVOUS', 'SIMPLE', name='accidentseverity'), nullable=False),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.Integer(), nullable=True),
    sa.Column('vehicles_involved', sa.Integer(), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_spot_id'], ['highway_black_spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_records_accident_date'), 'accident_records', ['accident_date'], unique=False)
    op.create_index(op.f('ix_accident_records_black_spot_id'), 'accident_records', ['black_spot_id'], unique=False)
    op.create_index('ix_accident_records_date_severity', 'accident_records', ['accident_date', 'severity'], unique=False)
    op.create_index(op.f('ix_accident_records_id'), 'accident_records', ['id'], unique=False)
    op.create_index('ix_accident_records_lat_lon', 'accident_records', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_accident_records_latitude'), 'accident_records', ['latitude'], unique=False)
    op.create_index(op.f('ix_accident_records_longitude'), 'accident_records', ['longitude'], unique=False)
    op.create_index(op.f('ix_accident_records_severity'), 'accident_records', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accident_records_severity'), table_name='accident_records')
    op.drop_index(op.f('ix_accident_records_longitude'), table_name='accident_records')
    op.drop_index(op.f('ix_accident_records_latitude'), table_name='accident_records')
    op.drop_index('ix_accident_records_lat_lon', table_name='accident_records')
    op.drop_index(op.f('ix_accident_records_id'), table_name='accident_records')
    op.drop_index('ix_accident_records_date_severity', table_name='accident_records')
    op.drop_index(op.f('ix_accident_records_black_spot_id'), table_name='accident_records')
    op.drop_index(op.f('ix_accident_records_accident_date'), table_name='accident_records')
    op.drop_table('accident_records')
    op.drop_index(op.f('ix_road_segment_risks_start_longitude'), table_name='road_segment_risks')
    op.drop_index(op.f('ix_road_segment_risks_start_latitude'), table_name='road_segment_risks')
    op.drop_index('ix_road_segment_risks_score', table_name='road_segment_risks')
    op.drop_index('ix_road_segment_risks_lat_lon', table_name='road_segment_risks')
    op.drop_index(op.f('ix_road_segment_risks_id'), table_name='road_segment_risks')
    op.drop_table('road_segment_risks')
    op.drop_index(op.f('ix_highway_black_spots_severity'), table_name='highway_black_spots')
    op.drop_index(op.f('ix_highway_black_spots_longitude'), table_name='highway_black_spots')
    op.drop_index(op.f('ix_highway_black_spots_latitude'), table_name='highway_black_spots')
    op.drop_index('ix_highway_black_spots_lat_lon', table_name='highway_black_spots')
    op.drop_index(op.f('ix_highway_black_spots_id'), table_name='highway_black_spots')
    op.drop_table('highway_black_spots')
    # ### end Alembic commands ###
